cyclomatic_complexity:
  ignores_case_statements: true
line_length:
  ignores_urls: true
identifier_name:
  min_length:
    warning: 1
    error: 1
function_body_length:
  warning: 100
  error: 150
type_body_length:
  warning: 300
  error: 500
excluded:
  - Packages/
  - Shared/Contrib
